export const Data = [
    {
        id: 1,
        month: 'Tháng 1',
        revenueData: 144,
        profitData: 423,
        loanData: 12,
    },
    {
        id: 2,
        month: 'Tháng 2',
        revenueData: 214,
        profitData: 345,
        loanData: 12,
    },
    {
        id: 3,
        month: 'Tháng 3',
        revenueData: 120,
        profitData: 555,
        loanData: 12,
    },
    {
        id: 4,
        month: 'Tháng 4',
        revenueData: 187,
        profitData: 455,
        loanData: 12,
    },
    {
        id: 5,
        month: 'Tháng 5',
        revenueData: 175,
        profitData: 234,
        loanData: 12,
    },
    {
        id: 6,
        month: 'Tháng 6',
        revenueData: 148,
        profitData: 234,
        loanData: 12,
    },
    {
        id: 7,
        month: 'Tháng 7',
        revenueData: 226,
        profitData: 234,
        loanData: 12,
    },
    {
        id: 8,
        month: 'Tháng 8',
        revenueData: 194,
        profitData: 393,
        loanData: 12,
    },
    {
        id: 9,
        month: 'Tháng 9',
        revenueData: 214,
        profitData: 345,
        loanData: 12,
    },
    {
        id: 10,
        month: 'Tháng 10',
        revenueData: 150,
        profitData: 555,
        loanData: 12,
    },
    {
        id: 11,
        month: 'Tháng 11',
        revenueData: 187,
        profitData: 455,
        loanData: 12,
    },
    {
        id: 12,
        month: 'Tháng 12',
        revenueData: 175,
        profitData: 234,
        loanData: 12,
    },
];
